IP_VERSION_4 = 'ipv4'
IP_VERSION_6 = 'ipv6'

PROTOCOL_TYPE_TCP = 'tcp'
PROTOCOL_TYPE_UDP = 'udp'
PROTOCOL_TYPE_ICMP = 'icmp'

ICMP_ANY = 'any'
ICMP_ECHO_REP = 'echo-reply'
ICMP_ECHO_REQ = 'echo-request'

ACTION_DENY = 'DPOR'
ACTION_ALLOW = 'ACCEPT'
